import { columns } from "./columns";
import { DataTable } from "./data-table";

function getData() {
    // Fetch data from your API here.
    return [
        {
            company: "Tech Corp",
            position: "Software Engineer",
            location: "New York, NY",
            status: "Applied",
            setup: "Onsite",
            date_applied: "2023-10-01",
            salary: "$120,000",
            contact_person: "John Doe",
            link: "https://example.com/job/1",
        },
        {
            company: "Innovatech",
            position: "Data Scientist",
            location: "San Francisco, CA",
            status: "Interview Scheduled",
            setup: "Remote",
            date_applied: "2023-09-15",
            salary: "$130,000",
            contact_person: "Jane Smith",
            link: "https://example.com/job/2",
        },
        {
            company: "Web Solutions",
            position: "Frontend Developer",
            location: "Austin, TX",
            status: "Rejected",
            setup: "Onsite",
            date_applied: "2023-08-20",
            salary: "$110,000",
            contact_person: "Alice Johnson",
            link: "https://example.com/job/3",
        },
        {
            company: "Cloud Services",
            position: "DevOps Engineer",
            location: "Seattle, WA",
            status: "Offer Received",
            setup: "Remote",
            date_applied: "2023-07-10",
            salary: "$140,000",
            contact_person: "Bob Brown",
            link: "https://example.com/job/4",
        },
        {
            company: "AI Innovations",
            position: "Machine Learning Engineer",
            location: "Boston, MA",
            status: "In Review",
            setup: "Hybrid",
            date_applied: "2023-06-05",
            salary: "$150,000",
            contact_person: "Charlie Green",
            link: "https://example.com/job/5",
        },
        {
            company: "Cybersecurity Inc.",
            position: "Security Analyst",
            location: "Chicago, IL",
            status: "Applied",
            setup: "Onsite",
            date_applied: "2023-05-15",
            salary: "$125,000",
            contact_person: "Diana White",
            link: "https://example.com/job/6",
        },
        {
            company: "FinTech Solutions",
            position: "Blockchain Developer",
            location: "Miami, FL",
            status: "Interview Scheduled",
            setup: "Remote",
            date_applied: "2023-04-25",
            salary: "$135,000",
            contact_person: "Ethan Black",
            link: "https://example.com/job/7",
        },
        {
            company: "HealthTech",
            position: "Full Stack Developer",
            location: "Los Angeles, CA",
            status: "Rejected",
            setup: "Hybrid",
            date_applied: "2023-03-30",
            salary: "$115,000",
            contact_person: "Fiona Blue",
            link: "https://example.com/job/8",
        },
        {
            company: "E-commerce Solutions",
            position: "UX/UI Designer",
            location: "Denver, CO",
            status: "Offer Received",
            setup: "Onsite",
            date_applied: "2023-02-20",
            salary: "$105,000",
            contact_person: "George Yellow",
            link: "https://example.com/job/9",
        },
        {
            company: "Gaming Studio",
            position: "Game Developer",
            location: "Portland, OR",
            status: "In Review",
            setup: "Remote",
            date_applied: "2023-01-10",
            salary: "$145,000",
            contact_person: "Hannah Purple",
            link: "https://example.com/job/10",
        },
        {
            company: "Logistics Solutions",
            position: "Systems Analyst",
            location: "Atlanta, GA",
            status: "Applied",
            setup: "Hybrid",
            date_applied: "2022-12-01",
            salary: "$120,000",
            contact_person: "Ian Orange",
            link: "https://example.com/job/11",
        },
        {
            company: "Retail Innovations",
            position: "Marketing Specialist",
            location: "Dallas, TX",
            status: "Interview Scheduled",
            setup: "Onsite",
            date_applied: "2022-11-15",
            salary: "$95,000",
            contact_person: "Jill Pink",
            link: "https://example.com/job/12",
        },
        {
            company: "Travel Tech",
            position: "Product Manager",
            location: "Phoenix, AZ",
            status: "Rejected",
            setup: "Remote",
            date_applied: "2022-10-05",
            salary: "$130,000",
            contact_person: "Kevin Gray",
            link: "https://example.com/job/13",
        },
        {
            company: "Education Solutions",
            position: "Content Writer",
            location: "San Diego, CA",
            status: "Offer Received",
            setup: "Hybrid",
            date_applied: "2022-09-20",
            salary: "$85,000",
            contact_person: "Laura Silver",
            link: "https://example.com/job/14",
        },
        {
            company: "Real Estate Tech",
            position: "Data Analyst",
            location: "Philadelphia, PA",
            status: "In Review",
            setup: "Onsite",
            date_applied: "2022-08-15",
            salary: "$110,000",
            contact_person: "Mike Gold",
            link: "https://example.com/job/15",
        },
        {
            company: "Media Solutions",
            position: "Video Editor",
            location: "Washington, DC",
            status: "Applied",
            setup: "Remote",
            date_applied: "2022-07-01",
            salary: "$95,000",
            contact_person: "Nina Bronze",
            link: "https://example.com/job/16",
        },
        {
            company: "Consulting Group",
            position: "Business Analyst",
            location: "Boston, MA",
            status: "Interview Scheduled",
            setup: "Hybrid",
            date_applied: "2022-06-10",
            salary: "$125,000",
            contact_person: "Oscar Copper",
            link: "https://example.com/job/17",
        },
        {
            company: "Non-Profit Org.",
            position: "Community Manager",
            location: "Seattle, WA",
            status: "Rejected",
            setup: "Onsite",
            date_applied: "2022-05-20",
            salary: "$70,000",
            contact_person: "Paula Steel",
            link: "https://example.com/job/18",
        },
        {
            company: "Energy Solutions",
            position: "Environmental Scientist",
            location: "Houston, TX",
            status: "Offer Received",
            setup: "Remote",
            date_applied: "2022-04-15",
            salary: "$115,000",
            contact_person: "Quentin Wood",
            link: "https://example.com/job/19",
        },
        {
            company: "Telecom Innovations",
            position: "Network Engineer",
            location: "Miami, FL",
            status: "In Review",
            setup: "Hybrid",
            date_applied: "2022-03-05",
            salary: "$130,000",
            contact_person: "Rachel Stone",
            link: "https://example.com/job/20"
        }
    ];
}

export default function JobListContent() {
    const data = getData();

    return (
        <div className="container mx-auto">
            <DataTable columns={columns} data={data} />
        </div>
    );
}